### ISSUE TITLE
Deploy new site to redirect to readthedocs.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/webapp2#108]

**Comment by cdman** [comment]
Does this mean updating "http://webapp-improved.appspot.com/" to redirect to "http://webapp2.readthedocs.io"? That would be great since the former is referenced from multiple places (including the official GAE documentation in some places I think).

**Comment by jonparrott** [comment]
Yes, this is ready to go I just haven't had time to do it. Hopefully sometime this week or next.

**Comment by cdman** [comment]
:bow: thank you!

**Comment by jonparrott** [comment]
This is done.
