### ISSUE TITLE
Readme file points to old forum

### ISSUE THREAD

**Issue by cdman** [GoogleCloudPlatform/webapp2#113]
The README.rst file (ie. https://github.com/GoogleCloudPlatform/webapp2/blob/master/README.rst) points to the old discussion group (https://groups.google.com/forum/#!forum/webapp2) however that one is mostly abandoned. Perhaps it should be updated to point to https://groups.google.com/forum/#!forum/google-appengine?

Cheers!

**Comment by cdman** [comment]
Also, it links to the webapp2 twitter account which seems to be abandoned...

**Comment by jonparrott** [comment]
Thanks, I'll try to get this updated shortly.

**Comment by cdman** [comment]
:bow: thank you!
