### ISSUE TITLE
Question: Is it still under development?

### ISSUE THREAD

**Issue by mymtwcom** [GoogleCloudPlatform/webapp2#114]
Does webapp2 under development?
I just remember, that google stopped to support it
Any roadmap for next version?

**Comment by jonparrott** [comment]
> Does webapp2 under development?

Webapp2 is community maintained and I am the current steward. I am not actively developing this project, but I do volunteer my time to review pull requests, respond to issues, and make releases when needed.

> I just remember, that google stopped to support it

Webapp2 is not a Google product, it was started by member of the Google App Engine community. Google Cloud Platform has offered to help the community maintain the project.

> Any roadmap for next version?

We have a milestone for the [3.0.0 release](https://github.com/GoogleCloudPlatform/webapp2/issues?q=is%3Aopen+is%3Aissue+milestone%3A%223.0.0+Release%22). I'm happy to review PRs to that end.
