### ISSUE TITLE
Any roadmap on this framework?

### ISSUE THREAD

**Issue by janscas** [GoogleCloudPlatform/webapp2#120]
Can any of you guys give me any reason to use webapp2 over other frameworks?

This project has been abandoned for a long time and there are no news other than some cleanup and "maybe" some python 3 compatibility.

Thanks

**Comment by jonparrott** [comment]
> Can any of you guys give me any reason to use webapp2 over other frameworks?

No one here is trying to sell you anything. If you want to use webapp2, go right ahead. If you don't, that's ok too. Personally, I recommend that users who are unencumbered by legacy to use frameworks with significantly larger communities such as Flask or Django.

> This project has been abandoned for a long time

Indeed it was, it is now maintained by Google Cloud Platform's Developer Relations team, but we are not actively making improvements to it. We are here to facilitate any community-driven improvements to the library (For example, @mymtwcom did the work to support Python 3). You can read more about the transfer of ownership [here](https://groups.google.com/forum/#!topic/google-appengine/PWKcZbKOj1U).

> Thanks

Thank you! I'm happy to answer any more questions, but I'm gonna go ahead and close this issue. :)
