### ISSUE TITLE
ipdb support for webapp2

### ISSUE THREAD

**Issue by kishan3** [GoogleCloudPlatform/webapp2#121]
Hi guys I am coming django background I am unable to get into debugging mode as we do in django and flask. 

I have installed ipdb using pip but my webapp2 application says `ImportError: No module named ipdb` .

I have also tried taking the app inside virtualenv (although its not necessary I guess ) still it doesn't work.

**Comment by mymtwcom** [comment]
I didn't use ipdb, but `pudb` worked for me.
Can you install it and put this into your code`import pudb;pudb.set_trace()`? Will it work?

**Comment by jonparrott** [comment]
@kishan3 are you using App Engine? It's quite possible that app engine is preventing using ipdb. Can you try using regular `pdb`?

**Comment by kishan3** [comment]
@jon yes i tried pdb and it works. But as you know ipdb is much better. Any idea why ipdb is not supported ? I would like to contribute for this requirement.

**Comment by jonparrott** [comment]
I don't think webapp2 specifically is stopping you from using ipdb. Are you
using app engine?

**Comment by kishan3** [comment]
Yes i am using app engine. I get the error `ImportError : No module named termios` . 
I googled about it but termios issue is  related to windows OS it seems. I use ubuntu.

**Comment by mymtwcom** [comment]
this is not windows related issue. gae trying to hide stdlib libraries. Issue not related with web framework. 
`I would like to contribute for this requirement.`
Im afraid that they will not implement this

**Comment by kishan3** [comment]
@mymtwcom any links to solve this specifically for Linux?

**Comment by jonparrott** [comment]
Unfortunately there's nothing we can do in this library to get ipdb to work in app engine. There's an [issue](https://code.google.com/p/googleappengine/issues/detail?id=7256) on App Engine, I suggest starring it to let them know that this is a desired feature.

I'm closing this issue for now, but feel free to continue to discuss.
