### ISSUE TITLE
Old webob library in 2.5.2

### ISSUE THREAD

**Issue by jonathan-s** [GoogleCloudPlatform/webapp2#122]
I'm using google appengine and they are not ready to include the latest version of webapp2 in their SDK (v3.0.0b1), because it might break the python runtime stability. 

So the problem I'm having is that `webapp2 2.5.2` is using `webob 1.2.2`. In that version status code 429 is not accepted. So I would like to kindly ask you to upgrade `webapp2` to `2.5.3` using `webob 1.3` where this issue is fixed. 

Would that be possible?

**Comment by jonparrott** [comment]
You should just be able to use webob 1.3 by specifying the version directly in your requirements.txt. Let me know if that doesn't work.

**Comment by anfedorov** [comment]
Of course, but GAE probably won't upgrade to his branch of webapp2 2.5.3 with webob 1.3, but probably will if you do?

**Comment by anfedorov** [comment]
(speaking as someone also interested in getting the upstream changes and fixes you're making into the GAE runtime)

**Comment by jonathan-s** [comment]
@jonparrott I have the requirements installed through a virtual environment and in that virtual environment I have a later version of webob. The webob version that is being picked up though is the one in the SDK.

**Comment by jonparrott** [comment]
@jonathan-s strange - are you using the `vendor` library in `appengine_config.py`? Can you share a simple app that can reproduce the problem?

@anfedorov upgrading the GAE managed version is surprisingly difficult, we're hoping to move away from that to a more general solution. No firm plans there yet.

**Comment by jonathan-s** [comment]
@jonparrott I had some settings for `appengine_config.py` but even if I deleted the file I still got failing tests when running my testsuite. The odd thing is that when running the testsuite in travis, it works properly. This is what made me think it was an osx specific issue.

**Comment by jonparrott** [comment]
@jonathan-s gotcha. Okay, without any further info I can't do anything. Let me know if you can figure out steps to reproduce.
