### ISSUE TITLE
Documentation update : New note in route guide - regex groups

### ISSUE THREAD

**Issue by k-antonius** [GoogleCloudPlatform/webapp2#123]
I'd like to add and explicit note indicating that if a regex group is included in the route, a matching positional argument parameter must be included in all handler methods that handle requests from that route.

I don't think this is explicit in the docs as currently written, and knowing this would have saved me quite a bit of time the other day.

**Comment by jonparrott** [comment]
@k-antonius which docs? Are they in this repo? If so, feel free to just send a PR.

**Comment by k-antonius** [comment]
They are in the this repo, so I will send a PR.

**Comment by jonparrott** [comment]
Closed by #124
