### ISSUE TITLE
ETA on 3.0.0?

### ISSUE THREAD

**Issue by tterrace** [GoogleCloudPlatform/webapp2#141]
Hi, is there a timeline for the 3.0.0 release? I've been using the beta to test out python3 functionality but I'd rather not use that in production if possible. 

Thanks!

**Comment by theacodes** [comment]
Draft the release PR, and I'll merge.

Cutting 3.0 does not imply any more support than what's currently present here. It's a community supported projects, bugs will need to be fixed by the community.

**Comment by gerardsimons** [comment]
I think it should be listed on the homepage which branch with what features are available for which python version
