### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [GoogleCloudPlatform/webapp2#40]
```
now it's time to give support to Python 3
```

Original issue reported on code.google.com by `alioy...@gmail.com` on 15 Dec 2011 at 3:53

**Comment by danbri** [comment]
@jonparrott what does the closure of this issue mean?

**Comment by theacodes** [comment]
The latest version support Python 3.

**Comment by danbri** [comment]
That's great! :)

**Comment by Chez** [comment]
I can find no reference to this on the Google Docs, can anyone point me to the fact that webapp2 is officially supporting python3?

**Comment by theacodes** [comment]
@Chez there was indeed work done to support Python in the webapp2 v3.0.0b1, and as far as I know it's complete.

All it would take at this point is someone taking the initiative to send a PR to cut the v3.0.0 release.

**Comment by theacodes** [comment]
Also keep in mind there is no "official" support of anything. This is a community-supported project and it's hosted here for governance reasons.

**Comment by jkevingutierrez** [comment]
The documentation https://webapp2.readthedocs.io/en/latest/#requirements says: 

webapp2 is compatible with Python 2.5 and superior. No Python 3 yet.
